### ISSUE TITLE
Updating PyPI

### ISSUE THREAD

**Issue by remram44** [ICSI-RealML/realML#3]
Hi there,

We are trying to push the primitives to PyPI. We noticed that there are changes in this repository that were never released to PyPI, although the primitive annotations were updated. The [`realML` package on PyPI](https://pypi.org/project/realML/) seems to belong to @alexgittens and points to another repository at https://github.com/alexgittens/realML.

Would it be possible to release a version on PyPI with the changes, or give me access to do so? If you would rather not, I will have to fork and rename the package so I can publish it to PyPI.

Thanks
-- Rémi

**Comment by gittea-rpi** [comment]
Hi Remi, if you give me your username on PyPI I'll add you as a maintainer so you can release versions.

**Comment by remram44** [comment]
Thanks, my username is [`remram`](https://pypi.org/user/remram/)
